CREATE TABLE pin_code (
    pin_id BIGINT GENERATED BY DEFAULT AS IDENTITY  PRIMARY KEY ,
    pin_code BIGINT,
    city_id BIGINT,
    state_id BIGINT,
    created_at  TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    deleted_at  TIMESTAMP WITHOUT TIME ZONE,
    update_at  TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    pin_status VARCHAR(20),
    CONSTRAINT fk_pin_city FOREIGN KEY (city_id) REFERENCES city(city_id),
    CONSTRAINT fk_pin_state FOREIGN KEY (state_id) REFERENCES state(state_id)
);